### ISSUE TITLE
Wallet/Private Keys backup not working.

### ISSUE THREAD

**Issue by jjl014** [btcz/bitcoinz-wallet#20]
Trying to backup my wallet or saving my private keys gives me an error.

"An unexpected error occured while backing up the wallet! Error response from wallet: error code: -4. error message: Cannot backup wallet until the -exportdir option has been set"

However, I can save single keys by right clicking them and obtaining them in the own addresses tab.

**Comment by cryptorex** [comment]
you can use something like:

`zcash-cli dumpwallet "C:\PathTo\Backup\keys.txt"`
