### ISSUE TITLE
Sent BTCZ to wallet address confirmed on blockchain 

### ISSUE THREAD

**Issue by Radar166** [btcz/bitcoinz-wallet#24]
Sent BTCZ to a wallet address and it is confirmed on the blockchain but no BTCZ arrived in the receivers wallet.  Thoughts?  Receiving address is correct.   Link to the transaction on the blockchain provided here [https://bitcoinz.ph/tx/501564beeb0523b340be1ffd7be0f364c3f3e790f041c89a2553f90b61aeb96d](url)

**Comment by cryptorex** [comment]
stale.
