### ISSUE TITLE
A general uexpected critical error

### ISSUE THREAD

**Issue by Siouxx0612** [btcz/bitcoinz-wallet#28]
Would anyone know what is this about and how to fix it?

[main] [Fri Jan 26 19:45:12 CET 2018] [INFO] zcashd is not runing at the moment or has not started/synchronized 100% - showing splash...
[main] [Fri Jan 26 19:45:12 CET 2018] [INFO] Splash: checking if zcashd is already running...
[main] [Fri Jan 26 19:45:13 CET 2018] [INFO] Splash: zcashd will be started...
[main] [Fri Jan 26 19:45:27 CET 2018] [ERROR] Unexpected error:
java.io.IOException: error: couldn't connect to server: EOF reached (code 1)
(make sure server is running and you are connecting to the correct RPC port)
        at com.vaklinov.zcashui.ZCashClientCaller.getDaemonRawRuntimeInfo(ZCashClientCaller.java:172)
        at com.vaklinov.zcashui.StartupProgressDialog.waitForStartup(StartupProgressDialog.java:131)
        at com.vaklinov.zcashui.ZCashUI.main(ZCashUI.java:557)

**Comment by SatoshiNakamoto** [comment]
yep, i had this problem too

**Comment by Siouxx0612** [comment]
I have reinstalled Windows, and the issue is gone,....
Works just fine now,....
something went wrong during initial setup i guess

**Comment by mbennette68** [comment]
I've had the BitcoinZ Wallet 1.1.0_1.3 for a month now, without issues, but suddenly last week or so, it started having above issue. I think this needs to be looked at as re-installing the OS is not really a practical solution.  I'm going to see if version 1.4 will help.  But somebody needs to take a look at what's causing the error.

**Comment by ccoapoyo** [comment]
I have this issue, download the latest version of wallet, backup de appdata folder, install the new version, and still remain this failure

**Comment by fernandopro333** [comment]
Get the feeling we are being ignored here.....

**Comment by solobos** [comment]
i have got same problem today. Can someone help us?

**Comment by RospyCrypto** [comment]
https://youtu.be/FhCP9Hot6k0

**Comment by Siouxx0612** [comment]
thank you RospyCrypto,...that works

**Comment by cryptorex** [comment]
https://github.com/btcz/bitcoinz-win/commit/9bbfcd842081a35c6f9b96078da3078b721ecbef
