### ISSUE TITLE
BTCZ Wallet Failure

### ISSUE THREAD

**Issue by fernandopro333** [btcz/bitcoinz-wallet#29]
Last week I experienced a full disk which caused BTCZ wallet to crash. Upon freeing up space I managed to to restart it, it seemed to try and rebuild the wallet history starting from Sept 7th,2017. Took a few hours however once it sync'd I never received my coins back. I have been trying ever since to no avail. Tried to backup the wallet days before but received an error, and never succeeded in creating a proper backup.  The actual error is already posted as an issue here by someone else. Even tried importing the old wallet but nothing happens. Have since created a new wallet file and using the transparent & private keys from the original wallet, tried to import them manually but the wallet complains citing invalid format...At a total loss...Have lost some significant coin can anyone help recover...?

**Comment by Siouxx0612** [comment]
sorry to hear that,...
Tbh i have similar issue. i exported keys, reinstalled OS and now keys don't work at all. Nothing happens.
Significant amount lost although somewhere inside hoping to find solution.

**Comment by fernandopro333** [comment]
Starting to suspect the BTCZ development group doesn't care....have not even been acknowledged. Doesn't say much about this ico.....I guess they are hoping for regulation to be imposed, if not they are asking for it.

**Comment by cryptorex** [comment]
stale issue - please open new issue with updated details if you're still experiencing problems.
