### ISSUE TITLE
Error 1: couldn't connect to server

### ISSUE THREAD

**Issue by piiich** [btcz/bitcoinz-wallet#30]
I'm getting this error every time I try to start the windows version of the wallet.
![bitcoinzwalleterror](https://user-images.githubusercontent.com/25477434/35830923-bf93e1b4-0a7c-11e8-9e55-6a675855e121.png)
I'm using the last version of the wallet.
Can you help me please?
Thanks a lot

**Comment by solobos** [comment]
i have got the same problem this morning

**Comment by 77qwerty** [comment]
I have got the same and it is for an unknown reason gone but wallet won't sync anymore and stuck on x percentage. Already reindexed and deleted everything in the bitcoinz folder except the wallet.dat file.

**Comment by RospyCrypto** [comment]
RospyCrypto
https://youtu.be/FhCP9Hot6k0

**Comment by piiich** [comment]
@RospyCrypto This method worked for me. Thanks!

**Comment by RospyCrypto** [comment]
I'm glad grats

**Comment by 77qwerty** [comment]
Still stuck on 83,14%. Problems started for me after installed Zclassic wallet which also uses zcashd daemon

**Comment by cryptorex** [comment]
stale issue - hashReserved issue addressed here: https://github.com/btcz/bitcoinz-win/commit/9bbfcd842081a35c6f9b96078da3078b721ecbef
