### ISSUE TITLE
Hello All, I just found a solution about critical error!!!

### ISSUE THREAD

**Issue by RospyCrypto** [btcz/bitcoinz-wallet#31]
Hello, Good Morning Guys I just found a solution for all of you guys because I had the same problem.
I have made a small video for you: 

https://youtu.be/FhCP9Hot6k0

**Comment by solobos** [comment]
thanks alot it is working now:)

**Comment by RospyCrypto** [comment]
I'm glad :)

**Comment by fernandopro333** [comment]
I hope I can still recover using the current wallet...

**Comment by RospyCrypto** [comment]
U can

**Comment by cannonballdex** [comment]
What happens when you have to do this every time you open the wallet. Takes forever to sync every time.

**Comment by RospyCrypto** [comment]
I suggest you download the wallet for Android or iPhone to your phone and transfer your balance there or keep it at TradeSatoshi

**Comment by fernandopro333** [comment]
Starting to think that's what the bitcoinZ team wants. After having mined so many coins people no longer have access to them and they don't lift a finger to help.

**Comment by RospyCrypto** [comment]
I suggest to everyone download the wallet for android or apple and move your coin there from this wallet that has issues or move them to TradeSatoshi

**Comment by cryptorex** [comment]
stale issue - seemed to have been hashReserved issue addressed here: https://github.com/btcz/bitcoinz-win/commit/9bbfcd842081a35c6f9b96078da3078b721ecbef
