### ISSUE TITLE
White form

### ISSUE THREAD

**Issue by digibum** [btcz/bitcoinz-wallet#32]
My wallet is showing only white empty window.... Only title of window is wisible "BitcoinZ Wallet 1.1.5.1"
Help?! Same with v 1.1.0.4...
//
Now I have tested this wallet on a different pc with same Windows version and it works there. So most be something with Windows...
//
Using Windows 10 Pro X64 1709 16299.192

**Comment by bitcoinz-pod** [comment]
checkout
https://github.com/bitcoinz-pod/bitcoinz-wallet/releases/download/1.1.5.1/bitcoinz-windows-wallet_1.1.5.1-2_win64.zip

backup your wallet.dat
delete all files from %appdata%/BitcoinZ and leave only wallet.dat
you can also run tools/reindex.bat

**Comment by edgaru** [comment]
same issue here, BitcoinZ Wallet 1.1.5.2

**Comment by cryptorex** [comment]
You need to make sure you're running the latest Java runtime on your computer.
