### ISSUE TITLE
I CAN NOT RESTORE THE WALLET THROUGH 12 WORDS ( BTCZ ) 

### ISSUE THREAD

**Issue by VahtangKyiv** [btcz/bitcoinz-wallet#43]
I CAN NOT RESTORE THE WALLET THROUGH 12 WORDS ( BTCZ ) 

WALLET MyBitcoinZ 10.0.1 

AFTER RESETTING WINDOWS, I TRIED TO RESTORE THE WALLET - 12 WORDS AND PASSWORD, BUT NOTHING HAPPENS WHAT HAPPENS? LIKE THIS FRAUD ?

**Comment by renuzit** [comment]
No, this is not fraud. MyBitcoinZ 10.0.1 is no longer supported. Please download a newer supported version of the wallet here: 
https://github.com/bitcoinz-wallets/bitcoinz-copay-wallet/releases

**Comment by VahtangKyiv** [comment]
Hello! Can 12 words coincide with the other participants? I could not restore my old wallet (MyBitcoinZ), I tried to create a new purse and used words and order from the old wallet, and everything went well, the question - where did my old balance in the amount of 12,800 BTCZ ??

**Comment by cryptorex** [comment]
What do you mean other participants?  If you mean a 12 word collision with another person, that is HIGHLY unlikely to occur.  

We can't tell you where your old balance is, only you know what you did.  If you used the same exact 12 words from your backup as the wallet that had the 12,800 BTCZ then you should see them.  If you don't the only thing to do is run a rescan after you successfully reimport with your 12 words by going to:

Go to Settings -> Select YOUR wallet -> More Options -> Addresses -> Scan Addresses for Funds
