### ISSUE TITLE
Selected folder when exporting Private Keys or Backup

### ISSUE THREAD

**Issue by eberlemartin** [btcz/bitcoinz-wallet#5]
When Clicking on Wallet -> Backup or Wallet -> Export private keys I get a FolderChooser to select where I want to store the file. The selected location is then completely ignored and the file is stored in %userdir%.

Luckily theres a message that tells you the actually used folder but it would be nice to either remove the FolderChooser or save files in the selected folder.

System: Win10 Pro 64 bit
Software: 1.1.0_1.2

**Comment by cryptorex** [comment]
the error should be that you need to specify -exportdir argument. 

you can instead run for example:

 `zcash-cli dumpwallet "C:\PathTo\Backup\keys.txt"`
