### ISSUE TITLE
Location wallet blockchain

### ISSUE THREAD

**Issue by 13Shum666** [btcz/bitcoinz-wallet#50]
Hello!
How to change the location wallet blockchain from "C:\Users\Admin\AppData\Roaming\BitcoinZ" to "E:\Wallets\BitCoinZ\Data"?

**Comment by cmar433** [comment]
move all your BitcoinZ data to another location you can create a symlink on Windows (on linux aswell, but you'll have to google that yourself).
Windows:

    Move content of %userprofile%\AppData\Roaming\BitcoinZ\ to folder in new location
    Start cmd with administrator privileges
    Type: mklink /J %userprofile%\AppData\Roaming\BitcoinZ "PathToNewLocation"

Then you have all BitcoinZ Data in that new location, also your wallet data etc...but blockchain should stay quite small for some time.

Just to be safe, have a backup from your wallet before you do that ;)
