### ISSUE TITLE
Missing sprout-proving key

### ISSUE THREAD

**Issue by FatThore** [btcz/bitcoinz-wallet#60]
While starting wallet for first time, dependency sprout-proving key is missing from repository

**Comment by cryptorex** [comment]
it's supposed to download it if it doesn't find it - is it not downloading it?

**Comment by fiinix00** [comment]
That file has been removed from this server: https://z.cash/downloads/sprout-proving.key

Possible new values are at: 
https://github.com/HorizenOfficial/zencash-swing-wallet-ui/blob/ae2f1039ed7301b837e31cb3e220f5a24da518c5/src/java/com/vaklinov/zcashui/ProvingKeyFetcher.java

https://downloads.horizen.io/file/TrustedSetup/sprout-proving.key
https://downloads.horizen.io/file/TrustedSetup/sprout-groth16.params
https://downloads.horizen.io/file/TrustedSetup/sapling-spend.params

https://download.z.cash/downloads/sprout-verifying.key

I downloaded theese manually and placed them in %APPDATA%\ZcashParams folder.

**Comment by FatThore** [comment]
Excellent!
Thank you so much for your help!

**Comment by cryptorex** [comment]
hmm ok thanks @fiinix00 - We'll have to update it, but probably will host it on a BTCZ resource.

**Comment by fiinix00** [comment]
Absolutely, would be wierd to leech on other peoples servers.

**Comment by cryptorex** [comment]
I'm updated the fetcher URL and tested.

Created new builds and updated them in the latest release.  Can someone please test?  If not I'll close this issue in 7 - 10 days I suppose. Thanks!

**Comment by fiinix00** [comment]
I cannot seem to find a pre-release of any kind, but based on the commit it appears to be correct (d.btcz.rocks/*)
Other than that, good work :)

**Comment by cryptorex** [comment]
Yeah I just replaced the binary releases in the latest release

**Comment by cryptorex** [comment]
addressed in commit: https://github.com/btcz/bitcoinz-wallet/commit/e51eb429c577d5bceaf8e787700b149d745afba2

closing issue - thanks everyone for your help!

**Comment by Dung40** [comment]
can you recommit and withdraw to my bitcoin wallet?

Vào 23:44, Th 3, 1 thg 6, 2021 cryptorex ***@***.***> đã viết:
