### ISSUE TITLE
Error message during startup "general unexpected critical error"

### ISSUE THREAD

**Issue by Shai0Hulud** [btcz/bitcoinz-wallet#61]
Error message I get when starting bitcoinz-wallet.exe
![image](https://user-images.githubusercontent.com/82765139/120365018-3ae55a80-c30e-11eb-86ef-240839f567cd.png)

bitcoinz.conf
![image](https://user-images.githubusercontent.com/82765139/120365234-7718bb00-c30e-11eb-9070-e2a3147007a9.png)

**Comment by cryptorex** [comment]
Please download the latest release zip file again.  We've updated it.

**Comment by Dung40** [comment]
I also don't understand what is this?

Vào 00:21, T.4, 2 Th6, 2021 Shai0Hulud ***@***.***> đã viết:

**Comment by cryptorex** [comment]
Please redownload the latest release again as already stated here: https://github.com/btcz/bitcoinz-wallet/releases/tag/v2.0.7

I'm locking this conversation as this issue has been addressed.
